### ISSUE TITLE
Create a grammar

### ISSUE THREAD

**Issue by jonathanvdc** [jonathanvdc/micron#1]
I guess this one's pretty self-explanatory: we need an LR(1) grammar to parse code with. I suggest we start off by creating a working prototype grammar for basic language constructs, such as let-bindings, type-declarations and a few basic expression types. That way, we can already get started on operator re-association and the semantic analysis pass while the grammar continues to grow.

**Comment by maurisvh** [comment]
We created a grammar. Hooray!
