### ISSUE TITLE
Extend the lexer

### ISSUE THREAD

**Issue by jonathanvdc** [jonathanvdc/micron#2]
The lexer can already handle most basic token types right now. Here's a list of tokens it can't read yet:
* Operator tokens
* Comments
* Various keywords and punctuation (but this depends on the grammar)

This shouldn't be too much work overall. Figuring out which tokens are operator tokens and which ones are punctuation could prove to be interesting, though.

**Comment by maurisvh** [comment]
The lexer was fully implemented.
