### ISSUE TITLE
Implement operators

### ISSUE THREAD

**Issue by jonathanvdc** [jonathanvdc/micron#3]
Implementing operators will require the following:
 1. Lexer support for operator tokens.
 2. A parser grammar rule for left-associated, precedence-agnostic operators.
 3. Operator reassociation in code - by manipulating parse trees.
 4. Some mechanism to convey operator precedence to the parser. 
     We could either create a grammar rule for this purpose, or we could
     implement function attributes in general, and create an operator precedence attribute.

The lexing, parsing and operator reassociation part should be pretty straightforward, unlike the last bullet, which involves some language design choices.

**Comment by maurisvh** [comment]
This was implemented.
